[app]
name = "Tildagen Arc Pong"
category = "Games"

[entry]
class = "TildagenApp"

[metadata]
author = "webboggles"
license = "CC-BY-NC-4.0"
url = "https://www.github.com/webboggles/tildagen-arc-pong"
description = "Circular breakout on the Tildagon. Tilt to steer a paddle round the edge, bash concentric brick rings, don't die."
version = "1.0.0"
